DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS solve;

CREATE TABLE task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    "description" TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE solve (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    "solve_time" INTEGER NOT NULL
);
